=== alenadkid/Portfolio-Aufgabenblatt-1-XML/pizza.dtd
<!ELEMENT Bestellung (Besteller, Pizza+)>
<!ELEMENT Besteller (Name, Anschrift, Student)>
<!ELEMENT Anschrift (Strasse, Hausnummer, PLZ, Ort)>
<!ELEMENT Student ((Matrikelnummer, Studienort) | keinStudent)>
<!ELEMENT Pizza (Belag+)>
<!ELEMENT Belag (#PCDATA)>
<!ATTLIST Belag Salami (scharf|nichtscharf) #IMPLIED>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Strasse (#PCDATA)>
<!ELEMENT Hausnummer (#PCDATA)>
<!ELEMENT PLZ (#PCDATA)>
<!ELEMENT Ort (#PCDATA)>
<!ELEMENT Matrikelnummer (#PCDATA)>
<!ELEMENT Studienort (#PCDATA)>
<!ELEMENT keinStudent EMPTY>

=== alenadkid/Portfolio-Aufgabenblatt-1-XML/BestellungNichtStudent.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Bestellung SYSTEM "pizza.dtd">
<Bestellung>
    <Besteller>
        <Name>DeMarco</Name>
        <Anschrift>
            <Strasse>Goethestra√üe</Strasse>
            <Hausnummer>31</Hausnummer>
            <PLZ>74076</PLZ>
            <Ort>Heilbronn</Ort>
        </Anschrift>
        <Student>
            <keinStudent/>
        </Student>
    </Besteller>
    <Pizza>
        <Belag>Schinken</Belag>
        <Belag>Mozzarella</Belag>
        <Belag Salami="scharf">Salami</Belag>
    </Pizza>
</Bestellung>

=== alenadkid/Portfolio-Aufgabenblatt-1-XML/BestellungStudent.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Bestellung SYSTEM "pizza.dtd">
<Bestellung>
    <Besteller>
        <Name>Ergin</Name>
        <Anschrift>
            <Strasse>Ranntalstraße</Strasse>
            <Hausnummer>8</Hausnummer>
            <PLZ>75196</PLZ>
            <Ort>Remchingen</Ort>
        </Anschrift>
        <Student>
            <Matrikelnummer>49862866</Matrikelnummer>
            <Studienort>Karlsruhe</Studienort>
        </Student>
    </Besteller>
    <Pizza>
        <Belag>Tomate</Belag>
        <Belag>Käse</Belag>
        <Belag Salami="scharf">Salami</Belag>
    </Pizza>
    <Pizza>
        <Belag>Knoblauch</Belag>
        <Belag>Schinken</Belag>
        <Belag>Rucola</Belag>
    </Pizza>
    <Pizza>
        <Belag>Thunfisch</Belag>
        <Belag>Zwiebel</Belag>
    </Pizza>
</Bestellung>
